### ISSUE TITLE
Project Load Error

### ISSUE THREAD

**Issue by thatonekriegerwriter** [Marin-MK/RPG-Studio-MK#47]
I was loading my v20 Project into MK, and I got this error
![image](https://github.com/Marin-MK/RPG-Studio-MK/assets/60249166/f5cbcc57-618c-49b0-b3f0-c3dc4b746ac1)

**Comment by Marin-MK** [comment]
It looks like you have metadata define in your map_metadata.txt PBS file for a non-existent map. Number 43 to be precise.

**Comment by Marin-MK** [comment]
This excess data will be trimmed out with the next build.
