### ISSUE TITLE
Project not loading- Egg Groups invalid

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Marin-MK/RPG-Studio-MK#48]
I was told to report this here, however I'm fairly certain this bug is because my own copy of Essentials is extremely modified.
![UK3xfJh](https://github.com/Marin-MK/RPG-Studio-MK/assets/15256630/570746da-78db-4d94-95dc-10ca4cc3f4ad)

Judging by what it says, it's because the egg groups are hardcoded currently, and it isn't accepting my custom egg groups.

**Comment by Marin-MK** [comment]
You can change the hardcoded data in the file called `hardcoded_data.json` in the program installation directory in `C:/Program Files/MK/RPG Studio MK` for the time being.

This will be editable through the editor in the future.
