### ISSUE TITLE
The value "GENTLE" is invalid. It must be one of  [..., "Gentle"...].

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Marin-MK/RPG-Studio-MK#50]
![DiEqy2s](https://github.com/Marin-MK/RPG-Studio-MK/assets/15256630/5f13b9f0-588a-4e45-9928-d51dc4ae5e05)

**Comment by Marin-MK** [comment]
It needs to be `Gentle`. It's case-sensitive currently.

**Comment by DerxwnaKapsyla** [comment]
I'm trying to find where it needs to be changed in my project, but the only places where the term `GENTLE` is being used that was by my hand is in trainers.txt, however by altering it there I make it so the game no longer compiles in RPG Maker XP. Is there something I'm overlooking or forgetting?

**Comment by Marin-MK** [comment]
Must be that old versions of Essentials used capitalized natures then. You could update `hardcoded_data.json` yourself, or wait a few releases until the hardcoded data system is reworked.

**Comment by Maruno17** [comment]
Which version of Essentials do you think you're using?

**Comment by DerxwnaKapsyla** [comment]
In my case, at the very least, I am using v21.1, with the latest hotfixes applied. So, this has me confused as well too.

**Comment by Marin-MK** [comment]
Then perhaps it's PBS from an old version of Essentials, but the v21.1 compiler is compatible with uppercase values?

**Comment by DerxwnaKapsyla** [comment]
I'm pretty sure it always has been... Like I mentioned, when I changed it to lowercase to test, it threw up an error saying that "Gentle" wasn't a valid nature.

**Comment by Marin-MK** [comment]
I will look into it further in that case.

**Comment by Marin-MK** [comment]
Natures have always been capitalized, at least they were in v17 and v21, so the nature data in `hardcoded_data.json` was wrong. This is what it should be:
```
	"natures": [
		"HARDY",
		"LONELY",
		"BRAVE",
		"ADAMANT",
		"NAUGHTY",
		"BOLD",
		"DOCILE",
		"RELAXED",
		"IMPISH",
		"LAX",
		"TIMID",
		"HASTY",
		"SERIOUS",
		"JOLLY",
		"NAIVE",
		"MODEST",
		"MILD",
		"QUIET",
		"BASHFUL",
		"RASH",
		"CALM",
		"GENTLE",
		"SASSY",
		"CAREFUL",
		"QUIRKY"
	],
```
