### ISSUE TITLE
adding new TMs/HMs not working properly

### ISSUE THREAD

**Issue by DarrylBD99** [Marin-MK/RPG-Studio-MK#60]
I am currently using RPG Studio MK v0.16.1 and there seems to be an issue with adding new TMs/HMs to the database. Whenever you add a new TM/HM, it defaults the FieldUse section as TR and the Pocket section as 0 (which doesn't exist and would lead to a compilation crash)

Here are some images of it:
![2023-10-14 (5)](https://github.com/Marin-MK/RPG-Studio-MK/assets/34701723/f7d574a4-f84c-4312-8ccb-d9926ce7fafb)
![2023-10-14 (6)](https://github.com/Marin-MK/RPG-Studio-MK/assets/34701723/cbb2ad0c-45de-4d73-a25f-28c6b48211fe)

**Comment by DarrylBD99** [comment]
oh and idk if it is just not implemented yet, but the Description section is empty

**Comment by Marin-MK** [comment]
These bugs have been fixed as of 085f599.
